version: "3.7"

services:
  gobarber_db:
    image: postgres
    container_name: postgresluizalabs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: luizalabs
      POSTGRES_DB: luizalabs
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  api:
    build: .
    container_name: luizalabsapi
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local
